export const ERROR_CODES = {
  E_UNAUTHORIZED: 'E_UNAUTHORIZED',
  E_UNAUTHORIZED_ACCESS: 'E_UNAUTHORIZED_ACCESS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  COIN_MARKET_SERVER_ERROR: 'COIN_MARKET_SERVER_ERROR',
  CASH_MARKET_SERVER_ERROR: 'CASH_MARKET_SERVER_ERROR',

  // Controllers
  CREATE_TRANSACTIONS_UNWISHED_ERROR: 'CREATE_TRANSACTIONS_UNWISHED_ERROR',
} as const
